version = 1

packages = [
  "tree", 
  "acpi",
  "alacritty",
  "base",
  "base-devel",
  "blender",
  "bluetui",
  "bluez",
  "bluez-utils",
  "bspwm",
  "chromium",
  "discord",
  "dolphin",
  "dunst",
  "efibootmgr",
  "firefox",
  "fuse2",
  "git",
  "grub",
  "gst-plugin-pipewire",
  "intel-media-driver",
  "intel-ucode",
  "iwd",
  "less",
  "lib32-mangohud",
  "libpulse",
  "libva-utils",
  "linux",
  "linux-firmware",
  "mangohud",
  "mc",
  "mkinitcpio",
  "nano",
  "networkmanager",
  "nnn",
  "pacman-contrib",
  "pipewire",
  "pipewire-alsa",
  "pipewire-jack",
  "pipewire-pulse",
  "power-profiles-daemon",
  "powertop",
  "python-gobject",
  "python-pip",
  "ranger",
  "reflector",
  "sof-firmware",
  "speedtest-cli",
  "steam",
  "sudo",
  "sxhkd",
  "thermald",
  "ttf-dejavu",
  "upower",
  "vim",
  "wireplumber",
  "xorg-server",
  "xorg-xinit",
  "xterm",
  "yazi",
  "zram-generator",
  "debtap",
  "fresh-editor-bin",
  "github-desktop-bin",
  "google-chrome",
  "neovim-git",
  "packettracer",
  "rust",
  "yay",
  "yay-debug",

]
